name       : deepin-icon-theme
version    : 15.12.58
release    : 1
source     :
    - https://github.com/linuxdeepin/deepin-icon-theme/archive/15.12.58.tar.gz : 302a1664f059b1cd199c89940dfa2baddae8de8bb5dbdc4111b95710e871e7e6
license    : GPL-3.0-or-later
component  : desktop.theme
patterns   :
    - sea  : /usr/share/icons/Sea
summary    : Standard Deepin icon theme + Deepin-SEA icon theme
description: |
    Icons from the Deepin Desktop Environment
setup      : |
    # nuke hicolor symbolic links
    sed -i 's/install: install-icons install-cursors hicolor-links/install: install-icons install-cursors/' Makefile
install    : |
    %make_install
