name       : deepin-icon-theme
version    : 15.12.69
release    : 5
source     :
    - https://github.com/linuxdeepin/deepin-icon-theme/archive/15.12.69.tar.gz : 72a22e22e0cfece4bb27f648a52f6df16fe9b205cda778c46c85b2b8061e46c1
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - dark : desktop.theme
    - sea : desktop.theme
patterns   :
    - dark : /usr/share/icons/deepin-dark
    - sea : /usr/share/icons/Sea
summary    :
    - Standard Deepin icon theme
    - dark : Deepin dark icon theme
    - sea : Deepin-SEA icon theme
description: |
    Icons from the Deepin Desktop Environment
builddeps  :
    - xcursorgen
rundeps    :
    - dark : deepin-icon-theme
    - sea : deepin-icon-theme
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-makefile.patch
build      : |
    %make
install    : |
    %make_install
