name       : deepin-icon-theme
version    : 15.12.66
release    : 3
source     :
    - https://github.com/linuxdeepin/deepin-icon-theme/archive/15.12.66.tar.gz : 9f78f978a7ad8b13f9f04aa68b7113a5a6c3a7b01cb785127bd9e4afc6faa971
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - dark : desktop.theme
    - sea : desktop.theme
patterns   :
    - dark : /usr/share/icons/deepin-dark
    - sea  : /usr/share/icons/Sea
summary    :
    - Standard Deepin icon theme
    - dark : Deepin dark icon theme
    - sea : Deepin-SEA icon theme
description: |
    Icons from the Deepin Desktop Environment
builddeps  :
    - xcursorgen
rundeps    :
    - dark : deepin-icon-theme
    - sea  : deepin-icon-theme
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-makefile.patch
build      : |
    %make
install    : |
    %make_install
