name       : deepin-icon-theme
version    : 15.12.59
release    : 2
source     :
    - https://github.com/linuxdeepin/deepin-icon-theme/archive/15.12.59.tar.gz : ec37f5d3d53d1cf46a383e650da25a69b31f2f5e92c0cb738a56bdff28247f50
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - sea  : desktop.theme
patterns   :
    - sea  : /usr/share/icons/Sea
summary    :
    - Standard Deepin icon theme
    - sea : Deepin-SEA icon theme
description: |
    Icons from the Deepin Desktop Environment
setup      : |
    # nuke hicolor symbolic links
    sed -i 's/install: install-icons install-cursors hicolor-links/install: install-icons install-cursors/' Makefile
install    : |
    %make_install
