name       : deepin-icon-theme
version    : 15.12.68
release    : 4
source     :
    - https://github.com/linuxdeepin/deepin-icon-theme/archive/15.12.68.tar.gz : abfe622aa3cadd833284edf6252d9220528791b444d26e701994ebd2a3e94475
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - dark : desktop.theme
    - sea : desktop.theme
patterns   :
    - dark : /usr/share/icons/deepin-dark
    - sea : /usr/share/icons/Sea
summary    :
    - Standard Deepin icon theme
    - dark : Deepin dark icon theme
    - sea : Deepin-SEA icon theme
description: |
    Icons from the Deepin Desktop Environment
builddeps  :
    - xcursorgen
rundeps    :
    - dark : deepin-icon-theme
    - sea : deepin-icon-theme
setup      : |
    %patch -p1 < $pkgfiles/0001-fix-makefile.patch
build      : |
    %make
install    : |
    %make_install
