name       : deepin-icon-theme
version    : 2020.04.13
release    : 8
source     :
    - https://github.com/linuxdeepin/deepin-icon-theme/archive/2020.04.13.tar.gz : 570271778ae71ffa62a93fb574171deb2da16558778cc547bbfc59625ca23599
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - dark : desktop.theme
    - sea : desktop.theme
summary    :
    - Standard Deepin icon theme
    - dark : Deepin dark icon theme
    - sea : Deepin Sea icon theme
description: |
    Icons from the Deepin Desktop Environment
patterns   :
    - dark : /usr/share/icons/deepin-dark
    - sea : /usr/share/icons/Sea
builddeps  :
    - xcursorgen
rundeps    :
    - dark : deepin-icon-theme
    - sea : deepin-icon-theme
setup      : |
    %apply_patches
build      : |
    %make
install    : |
    %make_install
