name       : deepin-icon-theme
version    : 2021.11.24
release    : 10
source     :
    - https://github.com/linuxdeepin/deepin-icon-theme/archive/refs/tags/2021.11.24.tar.gz : b4f4abddb7c3e8e9352078e78ef65c246a9e37ece2fc05c06b76f89de34d25c4
homepage   : https://github.com/linuxdeepin/deepin-icon-theme
license    : GPL-3.0-or-later
component  :
    - desktop.theme
    - bloom : desktop.theme
    - bloom-dark : desktop.theme
    - dark : desktop.theme
    - sea : desktop.theme
summary    :
    - Standard Deepin icon theme
    - bloom : Deepin bloom icon theme
    - bloom-dark : Deepin bloom icon theme
    - dark : Deepin dark icon theme
    - sea : Deepin Sea icon theme
description: |
    Icons from the Deepin Desktop Environment
patterns   :
    - bloom : /usr/share/icons/bloom
    - bloom-dark : /usr/share/icons/bloom-dark
    - dark : /usr/share/icons/deepin-dark
    - sea : /usr/share/icons/Sea
builddeps  :
    - xcursorgen
rundeps    :
    - deepin-icon-theme-bloom
    - bloom-dark : deepin-icon-theme
    - dark : deepin-icon-theme
    - sea : deepin-icon-theme
setup      : |
    sed -i -e 's|bloom-classic|deepin|g' */index.theme
    %patch -p1 < $pkgfiles/0001-Fix-Makefile.patch
build      : |
    %make
install    : |
    %make_install

    # Add icons for our Software Center
    pushd $installdir/usr/share/icons
    for theme in bloom deepin ; do
        cd ${theme}
        for sc in 16 24 32 48 64 96 128 256 512 ; do
            if [ -d "apps/${sc}" ] ; then
                 ln -sv deepin-app-store.svg apps/${sc}/system-software-install.svg
            fi
        done
        cd ..
    done
    popd

    # Remove broken icons and make symbolic links
    pushd $installdir/usr/share/icons
    rm bloom/apps/48/{calibre-gui.svg,galculator.svg,texmacs.svg,vim.svg}
    rm deepin/apps/48/{calibre-gui.svg,galculator.svg,libreoffice-*.svg,vim.svg}
    rm Sea/apps/scalable/{calibre-gui.svg,galculator.svg,libreoffice-*.svg,vim.svg}
    for theme in bloom bloom-dark; do    
    cd ${theme}
    rm places/16/folder-symbolic.svg
    ln -sv folder-downloads-symbolic.svg places/16/folder-download-symbolic.svg
    cd ..
    done
